services:

  mongodb:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB__USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB__PASSWORD}

    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  rate_limiter:
    build: ./rate_limiter
    restart: unless-stopped
    ports:
      - "12227:12227"
    networks:
      - app-network

  watcher:
    build:
      context: ./watcher
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV=PROD
    depends_on:
      - mongodb
      - rate_limiter
    networks:
      - app-network

  api:
    build:
      context: ./api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV=PROD
    depends_on:
      - mongodb
      - rate_limiter
    ports:
      - "8000:8000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
